In [ ]:
1+1

In [ ]:
2*2

In [ ]:
2/2

In [ ]:
4-5

In [ ]:
4**5

In [ ]:
a = 5**4

In [ ]:
a

In [ ]:
a = 6

In [ ]:
a

In [ ]:
a/6

In [ ]:
a = [1,3,4,8]

In [ ]:
a

In [ ]:
a*2

In [ ]:
a.append(2)

In [ ]:
a

In [2]:
import numpy as np

In [ ]:
a = np.array(a)

In [ ]:
a

In [ ]:
a*2

In [ ]:
a-1

In [ ]:
a**2

In [ ]:
a+a

In [ ]:
a*a

In [ ]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
b

In [ ]:
c = np.array([[2,2,4],[4,4,6],[8,8,6]])

In [ ]:
c

In [ ]:
b+c

In [ ]:
b*c

In [ ]:
b.shape

In [ ]:
d = np.array([b,b,b,b,c,c])

In [ ]:
d

In [ ]:
d.shape

In [3]:
dummy_picture = np.array([[ 0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
                          [ 0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
                          [ 0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
                          [ 0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
                          [ 0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
                          [ 0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
                          [ 0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
                          [ 0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
                          [ 0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
                          [ 0, 0, 1, 1, 1, 1, 1, 1, 0, 0]])

In [4]:
dummy_picture

array([[0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 1, 0, 0]])

In [5]:
many_dummy_pictures = np.array([dummy_picture,dummy_picture,dummy_picture,dummy_picture,dummy_picture])

In [6]:
many_dummy_pictures

array([[[0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
        [0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
        [0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
        [0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
        [0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
        [0, 0, 1, 1, 1, 1, 1, 1, 0, 0]],

       [[0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
        [0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
        [0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
        [0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
        [0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
        [0, 0, 1, 1, 1, 1, 1, 1, 0, 0]],

       [[0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
        [0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
        [0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 1, 1, 1, 1, 1, 0, 

In [7]:
many_dummy_pictures * np.array([[[1]],[[2]],[[3]],[[4]],[[5]]])

array([[[0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
        [0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
        [0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
        [0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
        [0, 0, 1, 1, 1, 1, 1, 1, 0, 0],
        [0, 0, 1, 1, 1, 1, 1, 1, 0, 0]],

       [[0, 0, 2, 2, 2, 2, 2, 2, 0, 0],
        [0, 0, 2, 2, 2, 2, 2, 2, 0, 0],
        [0, 0, 2, 2, 0, 0, 0, 0, 0, 0],
        [0, 0, 2, 2, 0, 0, 0, 0, 0, 0],
        [0, 0, 2, 2, 2, 2, 2, 2, 0, 0],
        [0, 0, 2, 2, 2, 2, 2, 2, 0, 0],
        [0, 0, 0, 0, 0, 0, 2, 2, 0, 0],
        [0, 0, 0, 0, 0, 0, 2, 2, 0, 0],
        [0, 0, 2, 2, 2, 2, 2, 2, 0, 0],
        [0, 0, 2, 2, 2, 2, 2, 2, 0, 0]],

       [[0, 0, 3, 3, 3, 3, 3, 3, 0, 0],
        [0, 0, 3, 3, 3, 3, 3, 3, 0, 0],
        [0, 0, 3, 3, 0, 0, 0, 0, 0, 0],
        [0, 0, 3, 3, 0, 0, 0, 0, 0, 0],
        [0, 0, 3, 3, 3, 3, 3, 3, 0, 